language: node_js
node_js:
  - '10.18.1'
cache:
  yarn: true
before_script:
  - yarn install
script:
  - yarn build
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
